export const categories = ["Tops", "Bottoms", "Outerwear", "Footwear", "Accessories"]

export const genders = ["women", "men"]

const color = {
  black: { name: "Black", hex: "#171717" },
  slate: { name: "Slate", hex: "#475569" },
  olive: { name: "Olive", hex: "#545a2f" },
  sand: { name: "Sand", hex: "#c2b280" },
  clay: { name: "Clay", hex: "#9a3412" },
  alpine: { name: "Alpine Blue", hex: "#1e3a5f" },
  forest: { name: "Forest", hex: "#14532d" },
  glacier: { name: "Glacier", hex: "#cbd5e1" },
  ember: { name: "Ember", hex: "#ea580c" },
  storm: { name: "Storm Grey", hex: "#6b7280" },
}

const apparelSizes = ["XS", "S", "M", "L", "XL"]
const shoeSizes = ["8", "9", "10", "11", "12"]
const oneSize = ["One Size"]

export const products = [
  {
    id: "w-rain-jacket",
    name: "Rain Jacket",
    gender: "women",
    category: "Outerwear",
    price: 279,
    onSale: true,
    salePrice: 219,
    colors: [color.alpine, color.black, color.ember],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "w-insulated-jacket",
    name: "Insulated Jacket",
    gender: "women",
    category: "Outerwear",
    price: 240,
    onSale: false,
    salePrice: null,
    colors: [color.clay, color.black, color.forest],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "w-fleece",
    name: "Fleece",
    gender: "women",
    category: "Tops",
    price: 120,
    onSale: false,
    salePrice: null,
    colors: [color.storm, color.alpine, color.sand],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "w-tshirt",
    name: "T-Shirt",
    gender: "women",
    category: "Tops",
    price: 75,
    onSale: true,
    salePrice: 55,
    colors: [color.glacier, color.black, color.clay],
    sizes: apparelSizes,
    icon: "tshirt",
  },
  {
    id: "w-tank-top",
    name: "Tank Top",
    gender: "women",
    category: "Tops",
    price: 55,
    onSale: false,
    salePrice: null,
    colors: [color.ember, color.slate, color.black],
    sizes: apparelSizes,
    icon: "tshirt",
  },
  {
    id: "w-hiking-pants",
    name: "Hiking Pants",
    gender: "women",
    category: "Bottoms",
    price: 145,
    onSale: false,
    salePrice: null,
    colors: [color.olive, color.black, color.sand],
    sizes: apparelSizes,
    icon: "pants",
  },
  {
    id: "w-shorts",
    name: "Shorts",
    gender: "women",
    category: "Bottoms",
    price: 80,
    onSale: true,
    salePrice: 60,
    colors: [color.sand, color.forest, color.black],
    sizes: apparelSizes,
    icon: "pants",
  },
  {
    id: "w-trail-shoes",
    name: "Trail Shoes",
    gender: "women",
    category: "Footwear",
    price: 165,
    onSale: false,
    salePrice: null,
    colors: [color.storm, color.ember, color.black],
    sizes: shoeSizes,
    icon: "sneaker",
  },
  {
    id: "w-hiking-boots",
    name: "Hiking Boots",
    gender: "women",
    category: "Footwear",
    price: 210,
    onSale: false,
    salePrice: null,
    colors: [color.clay, color.slate],
    sizes: shoeSizes,
    icon: "boot",
  },
  {
    id: "w-backpack",
    name: "Backpack",
    gender: "women",
    category: "Accessories",
    price: 130,
    onSale: false,
    salePrice: null,
    colors: [color.alpine, color.black, color.olive],
    sizes: oneSize,
    icon: "backpack",
  },
  {
    id: "w-beanie",
    name: "Beanie",
    gender: "women",
    category: "Accessories",
    price: 40,
    onSale: true,
    salePrice: 30,
    colors: [color.clay, color.black, color.glacier],
    sizes: oneSize,
    icon: "beanie",
  },
  {
    id: "w-cap",
    name: "Cap",
    gender: "women",
    category: "Accessories",
    price: 38,
    onSale: false,
    salePrice: null,
    colors: [color.sand, color.forest, color.black],
    sizes: oneSize,
    icon: "cap",
  },
  {
    id: "m-rain-jacket",
    name: "Rain Jacket",
    gender: "men",
    category: "Outerwear",
    price: 279,
    onSale: true,
    salePrice: 219,
    colors: [color.forest, color.black, color.alpine],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "m-hardshell-jacket",
    name: "Hardshell Jacket",
    gender: "men",
    category: "Outerwear",
    price: 320,
    onSale: false,
    salePrice: null,
    colors: [color.black, color.slate, color.ember],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "m-fleece",
    name: "Fleece",
    gender: "men",
    category: "Tops",
    price: 120,
    onSale: false,
    salePrice: null,
    colors: [color.slate, color.olive, color.black],
    sizes: apparelSizes,
    icon: "hoodie",
  },
  {
    id: "m-tshirt",
    name: "T-Shirt",
    gender: "men",
    category: "Tops",
    price: 75,
    onSale: true,
    salePrice: 55,
    colors: [color.black, color.glacier, color.alpine],
    sizes: apparelSizes,
    icon: "tshirt",
  },
  {
    id: "m-hoodie",
    name: "Hoodie",
    gender: "men",
    category: "Tops",
    price: 90,
    onSale: false,
    salePrice: null,
    colors: [color.sand, color.storm, color.forest],
    sizes: apparelSizes,
    icon: "tshirt",
  },
  {
    id: "m-hiking-pants",
    name: "Hiking Pants",
    gender: "men",
    category: "Bottoms",
    price: 145,
    onSale: false,
    salePrice: null,
    colors: [color.olive, color.black, color.sand],
    sizes: apparelSizes,
    icon: "pants",
  },
  {
    id: "m-cargo-pants",
    name: "Cargo Pants",
    gender: "men",
    category: "Bottoms",
    price: 130,
    onSale: true,
    salePrice: 99,
    colors: [color.storm, color.clay, color.black],
    sizes: apparelSizes,
    icon: "pants",
  },
  {
    id: "m-shorts",
    name: "Shorts",
    gender: "men",
    category: "Bottoms",
    price: 80,
    onSale: false,
    salePrice: null,
    colors: [color.sand, color.black, color.forest],
    sizes: apparelSizes,
    icon: "pants",
  },
  {
    id: "m-trail-shoes",
    name: "Trail Shoes",
    gender: "men",
    category: "Footwear",
    price: 165,
    onSale: false,
    salePrice: null,
    colors: [color.slate, color.ember, color.black],
    sizes: shoeSizes,
    icon: "sneaker",
  },
  {
    id: "m-hiking-boots",
    name: "Hiking Boots",
    gender: "men",
    category: "Footwear",
    price: 210,
    onSale: true,
    salePrice: 169,
    colors: [color.clay, color.black],
    sizes: shoeSizes,
    icon: "boot",
  },
  {
    id: "m-backpack",
    name: "Backpack",
    gender: "men",
    category: "Accessories",
    price: 140,
    onSale: false,
    salePrice: null,
    colors: [color.black, color.forest, color.alpine],
    sizes: oneSize,
    icon: "backpack",
  },
  {
    id: "m-cap",
    name: "Cap",
    gender: "men",
    category: "Accessories",
    price: 38,
    onSale: false,
    salePrice: null,
    colors: [color.olive, color.black, color.storm],
    sizes: oneSize,
    icon: "cap",
  },
]

export const newArrivals = products.filter((product) => product.onSale).slice(0, 8)

export const allColors = Array.from(
  new Map(products.flatMap((product) => product.colors).map((c) => [c.name, c])).values()
)

export const allSizes = Array.from(new Set(products.flatMap((product) => product.sizes)))

export const priceBuckets = [
  { label: "Under $50", min: 0, max: 50 },
  { label: "$50 to $100", min: 50, max: 100 },
  { label: "$100 to $200", min: 100, max: 200 },
  { label: "$200 and up", min: 200, max: Infinity },
]

export function priceOf(product) {
  return product.onSale ? product.salePrice : product.price
}
